import React,{useEffect,useState} from 'react';
import {Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {supabase} from '../lib/supabase';
export default function FreelancerManager(){const[list,setList]=useState([]),[busy,setBusy]=useState(false),[f,setF]=useState({full_name:'',email:'',phone:'',team_leader:''});
async function load(){const{data,error}=await supabase.from('freelancers').select('id,freelancer_number,full_name,email,phone,team_leader,status,created_at').order('created_at',{ascending:false});if(!error)setList(data||[])}useEffect(()=>{load()},[]);
const set=(k,v)=>setF(x=>({...x,[k]:v}));
async function onboard(){if(!f.full_name.trim()||!f.email.trim())return Alert.alert('Taarifa hazijakamilika','Jina kamili na email vinahitajika.');setBusy(true);const{data,error}=await supabase.functions.invoke('staff-onboard-freelancer',{body:{full_name:f.full_name.trim(),email:f.email.trim().toLowerCase(),phone:f.phone.trim()||null,team_leader:f.team_leader.trim()||null}});setBusy(false);if(error||data?.error)return Alert.alert('Onboarding imeshindikana',data?.error||error.message);Alert.alert('Freelancer ameidhinishwa',`${data.freelancer.full_name}\n${data.freelancer.freelancer_number}\n\nFreelancer atatengeneza password yake mwenyewe ndani ya Freelancer App baada ya kuthibitisha PIN ya tarakimu 6 kwenye email.`);setF({full_name:'',email:'',phone:'',team_leader:''});load()}
async function status(id,value){const{error}=await supabase.rpc('staff_set_freelancer_status',{p_freelancer_id:id,p_status:value});if(error)return Alert.alert('Imeshindikana',error.message);load()}
return <ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><Text style={s.title}>Freelancer Management</Text><Text style={s.note}>CEO na Directors walioidhinishwa pekee. Staff haiseti password. Freelancer anatengeneza password yake mwenyewe kwa PIN ya tarakimu 6 inayotumwa kwenye email yake.</Text>{[['full_name','Jina kamili'],['email','Email'],['phone','Simu'],['team_leader','Team Leader (optional)']].map(([k,p])=><TextInput key={k} style={s.input} placeholder={p} value={f[k]} onChangeText={v=>set(k,v)} autoCapitalize={k==='email'?'none':'words'} keyboardType={k==='email'?'email-address':k==='phone'?'phone-pad':'default'}/>)}<Pressable style={[s.btn,busy&&{opacity:.5}]} disabled={busy} onPress={onboard}><Text style={s.bt}>{busy?'Inaandaa account...':'Onboard & Activate Freelancer'}</Text></Pressable><Text style={s.heading}>Freelancers</Text>{list.map(x=><View key={x.id} style={s.card}><Text style={s.name}>{x.full_name}</Text><Text>{x.freelancer_number} • {x.status}</Text>{x.email?<Text>{x.email}</Text>:null}{x.phone?<Text>{x.phone}</Text>:null}<View style={s.row}>{x.status!=='ACTIVE'&&<Pressable style={s.small} onPress={()=>status(x.id,'ACTIVE')}><Text style={s.st}>Activate</Text></Pressable>}{x.status!=='SUSPENDED'&&<Pressable style={s.small} onPress={()=>status(x.id,'SUSPENDED')}><Text style={s.st}>Suspend</Text></Pressable>}{x.status!=='INACTIVE'&&<Pressable style={s.small} onPress={()=>status(x.id,'INACTIVE')}><Text style={s.st}>Inactive</Text></Pressable>}</View></View>)}</ScrollView>}
const s=StyleSheet.create({page:{padding:16,paddingBottom:70},title:{fontSize:24,fontWeight:'900',marginBottom:8},note:{backgroundColor:'#EFF4FA',padding:12,borderRadius:10,marginBottom:14,lineHeight:19},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#D9E2EC',borderRadius:10,padding:13,marginBottom:10},btn:{backgroundColor:'#1B4D89',padding:14,borderRadius:10,alignItems:'center'},bt:{color:'#fff',fontWeight:'800'},heading:{fontSize:18,fontWeight:'800',marginTop:24,marginBottom:10},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#D9E2EC',borderRadius:12,padding:14,marginBottom:10},name:{fontWeight:'900',fontSize:16,marginBottom:4},row:{flexDirection:'row',gap:8,marginTop:10,flexWrap:'wrap'},small:{backgroundColor:'#EFF4FA',paddingVertical:8,paddingHorizontal:12,borderRadius:8},st:{fontWeight:'700',color:'#1B4D89'}});